# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48934419b539ae8c6f1d73d9a4f33e346339385270f83fa03d96523d9469ee1787b76d6ba16d0051cea51b6fe2ec1f025198d02b177c3c649e91c199ad88c8bb

test:
  secret_key_base: 748c6ea946d16fc6784ac0885d75f4f717014b781ddd5250ffba0151f1a8da1647cf024ff40091b506f06b5b0eabbcc1758654e3517eadaf4af007aba664d47b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
